# The hyprmoncfg monitor-profile daemon and its state file seeding.
{ config, lib, pkgs, ... }:

let
  cfg = config.hyprland-config;
in
{
  config = lib.mkIf cfg.enable {
    # hyprland.lua does `require("monitors")`, expecting hyprmoncfgd to have
    # written ~/.config/hypr/monitors.lua. Seed a stub with hyprmoncfg's own
    # "generated" header on first activation only, so the daemon's real writes
    # afterward are never clobbered by a home-manager switch.
    home.activation.seedHyprMonitorsLua = config.lib.dag.entryAfter [ "writeBoundary" ] ''
      monitorsLua="$HOME/.config/hypr/monitors.lua"
      if [ ! -e "$monitorsLua" ]; then
        $DRY_RUN_CMD install -Dm644 ${pkgs.writeText "monitors.lua" "-- Generated by hyprmoncfg\n"} "$monitorsLua"
      fi
    '';

    systemd.user.services.hyprmoncfgd = {
      Unit = {
        Description = "Hyprland monitor profile daemon (hyprmoncfgd)";
        After = [ "hyprland-session.target" ];
        PartOf = [ "hyprland-session.target" ];
      };
      Service = {
        Type = "simple";
        ExecStart = "${pkgs.hyprmoncfg}/bin/hyprmoncfgd";
        Restart = "on-failure";
        RestartSec = 2;
      };
      Install = {
        WantedBy = [ "hyprland-session.target" ];
      };
    };
  };
}
