background {
    monitor =
    color = rgba(40, 42, 54, 1.0)
}

input-field {
    monitor =
    size = 300, 50
    outline_thickness = 2
    outer_color = rgb(bd93f9)
    inner_color = rgb(68, 71, 90)
    font_color = rgb(f8f8f2)
    fade_on_empty = true
    placeholder_text = <i>Password...</i>
    halign = center
    valign = center
}
